### ISSUE TITLE
Plotly Lab error

### ISSUE THREAD

**Issue by UpwardTrajectory** [learn-co-curriculum/plotly-lab#11]
the line below "From there, we can use our trace_values function to plot our chart.

Uncomment and run the code below" looks as follows, but the 'mode' should be 'lines' not 'line'.  If you simply uncomment the line and run it, it fails, but adding an 's' makes it work.

#trace2 = trace_values([1, 2, 3], [2, 4, 5], 'line', 'line trace')  
should become
#trace2 = trace_values([1, 2, 3], [2, 4, 5], 'lines', 'line trace')

**Comment by LoreDirick** [comment]
@UpwardTrajectory fixed, thanks!
