### ISSUE TITLE
Revised "Plot" Function Doesn't Use Layout

### ISSUE THREAD

**Issue by ddbrennan** [learn-co-curriculum/plotly-lab#2]
def plot(traces = [], layout = {}):
    if not isinstance(traces, list): raise TypeError('first argument must be a list.  Instead is', traces)
    if not isinstance(layout, dict): raise TypeError('second argument must be a dict.  Instead is', layout)
    plotly.offline.iplot({'data': traces, **'layout': {}**})

Last 'layout' should point to 'layout'

**Comment by matt-mcalister** [comment]
this seems like a valid issue for you david, but I don't know if this applies to the group

**Comment by matt-mcalister** [comment]
oh yeah, big time!
