### ISSUE TITLE
Plotly ValueError

### ISSUE THREAD

**Issue by josephbrockw** [learn-co-curriculum/plotly-lab#9]
<img width="737" alt="screen shot 2018-10-18 at 7 54 44 am" src="https://user-images.githubusercontent.com/11033221/47155787-3c6fca80-d2ab-11e8-9f72-e1652dfcb570.png">

<img width="984" alt="screen shot 2018-10-18 at 7 56 17 am" src="https://user-images.githubusercontent.com/11033221/47155840-590c0280-d2ab-11e8-8149-9e8bbb8b1071.png">

**Comment by L-Lewis** [comment]
I am having the same issue and also getting this error message. Did you find a solution?

**Comment by j-asonwang** [comment]
Hey, ran into this too! In case you're still stuck the solution is to edit 'line' (3rd arugment in trace_values) to 'lines'.

**Comment by LoreDirick** [comment]
Thanks for catching! Fixed it now, thanks!
@josephbrockw
